# Generated by Django 5.0.6 on 2024-07-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='loan_approve',
            new_name='loan_approval',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_bank_bankrupt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'Withdrawal'), (3, 'Loan'), (4, 'Loan Paid'), (5, 'Send money'), (6, 'Receive money')]),
        ),
    ]
